import { City } from './city.model';
import { District } from './district.model';
import { LaundryPackage } from './laundry-package.model';

export class UserProfile {
  accountId?: number;
  rank: string;
  memberType: string;
  registrationChannel?: string;
  id?: number;
  email?: string;
  fullname?: string;
  pin?: number;
  phone?: number;
  clubNameEn?: string;
  clubNameVi?: string;
  facebookId?: string;
  googleId?: string;
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  lastName?: string;
  firstName?: string;
  city?: string;
  district?: string;
  ward?: string;
  identifyNumber?: number;
  birthday?: string;
  avatar?: string;
  gender?: boolean;
  cityId?: number;
  clubId?: number;
  clubIds?: number[];
  clubKey?: string;
  clubKeys?: string[];
  districtId?: number;
  countryId?: number;
  roleId?: number;
  ocupationId?: string;
  accountType?: string;
  lastLogin?: string;
  firstLogin?: string;
  fingerEnroll?: boolean;
  idCardUploaded?: boolean;
  devices?: [];
  settings?: [];
  roles?: string[];
  permissions?: string[];
  systemPermissions?: string[];
  address?: string;
  cityDetail?: City;
  districtDetail?: District;
  paymentPlanDetail?: LaundryPackage[];
  memberContract?: any;
  statusContract?: string;
  idCardImage?: string;
  gmId?: string;
  ptId?: string;
  ptGroupId?: string;
  activated?: boolean;
  groupId?: string;
  groupName?: string;
}